### ISSUE TITLE
Versions after 1.18.0 fail to npm install

### ISSUE THREAD

**Issue by Sleaker** [amtrack/pmd-bin#39]
https://github.com/amtrack/pmd-bin/blob/master/package.json#L16

All versions published to npmjs.org after 1.18.0 wont work due to inability to npm install with some form of a missing file issue:
the current version just flat out fails to install because the download-java.js script is not included.

install.js also no longer exists but is still referenced in package.json

Suggestion: test packaging and releases in some fashion to prevent this issue in the future.

**Comment by amtrack** [comment]
@Sleaker Thanks for reporting this issue!
You're right, as this package now heavily depends on npm lifecycle scripts, we should add more E2E tests.
