### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [amtrack/pmd-bin#92]
I'm curious, can you give a small example on how to use it?

**Comment by amtrack** [comment]
Yes, of course. Here is a simple example:

```
pmd -dir force-app/main/default/classes -rulesets apex-style -language apex
```

**Comment by NilsBaumgartner1994** [comment]
Nice, can we use it in a JavaScript file itself or only terminal?Beste Grüße,Nils BaumgartnerAm 01.06.2023 um 20:20 schrieb Matthias Rolke ***@***.***>:﻿
Yes, of course. Here is a simple example:
pmd -dir force-app/main/default/classes -rulesets apex-style -language apex

**Comment by amtrack** [comment]
Only in the Terminal.
