### ISSUE TITLE
Java is downloaded even when it's already available

### ISSUE THREAD

**Issue by geoffswift** [amtrack/pmd-bin#95]
See below snippet which has `allow_system_java: false` (can we please have it set as `true` instead).  This setting means the JRE is downloaded every time we do an npm install.  As we're running pmd-bin in our CI environments this is affecting the performance of our builds and it's wasteful of network bandwidth as well.

```javascript
async function installJava() {
  const jre = require("node-java-connector");
  return jre
    .install({ feature_version: 17, type: "jre", allow_system_java: false })
 ```

**Comment by amtrack** [comment]
@geoffswift I created an alternative PR #97 to #96  which doesn't change the current behaviour of this package.
Instead, you can explicitly opt-out the java download by setting an environment variable:

```console
export PMD_BIN_SKIP_JAVA_DOWNLOAD="true"
npm install --global pmd-bin
```

Could you please confirm that this would also solve your issue?

**Comment by geoffswift** [comment]
There is a similar pattern followed for Pupeteer, whereby you can set the environment variable `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD`
